<a href="https://colab.research.google.com/github/j-agrawal/Machine-Learning/blob/master/ML(numpy)day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99,4])

In [20]:
print(a)

[ 2  7  1 99  4]


In [21]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [23]:
a

array([ 2,  7,  1, 99,  4])

In [24]:
b

array([ 12,  17,  11, 199,  14])

In [25]:
a[0]

2

In [26]:
b[0]

12

In [27]:
a+b

array([ 14,  24,  12, 298,  18])

In [28]:
a+2

array([  4,   9,   3, 101,   6])

In [29]:
a*2

array([  4,  14,   2, 198,   8])

In [30]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
x=np.array([[2,5,8], [3,6,1]])

In [32]:
print(x)

[[2 5 8]
 [3 6 1]]


In [33]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [34]:
x[0]

array([2, 5, 8])

In [37]:
x[0,0]

2

In [38]:
x[0,0]

2

In [39]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
y=x+7

In [41]:
y

array([[ 9, 12, 15],
       [10, 13,  8]])

In [42]:
x*2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [43]:
x**2

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [44]:
x**3

array([[  8, 125, 512],
       [ 27, 216,   1]])

In [45]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [46]:
x[1]

array([3, 6, 1])

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]])

In [48]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [49]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [50]:
x.shape

(2, 3)

In [51]:
z.shape

(4, 2)

In [52]:
z[0:2] #for printing range of rows...

array([[2, 7],
       [3, 8]])

In [53]:
z[0:] #printing all rows

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
#x[row:range,column:range]

In [55]:
z[0:]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [56]:
z[0:2,0]

array([2, 3])

In [57]:
x[0:,1]

array([5, 6])

In [58]:
x[0:,0:2]

array([[2, 5],
       [3, 6]])

In [59]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [61]:
z[2]

array([2, 9])

In [62]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [63]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [65]:
z[[0,3],[1]]

array([7, 4])

In [66]:
b=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])
b

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [67]:
b.shape

(4, 3)

In [73]:
b[0:4,[1]]


array([[9],
       [2],
       [5],
       [9]])

In [74]:
b[0:4,[2]]


array([[7],
       [8],
       [6],
       [0]])

In [75]:
b[0:,[2]]

array([[7],
       [8],
       [6],
       [0]])

In [76]:
b[1:3,[1]]

array([[2],
       [5]])

In [81]:
b[1:4,2]

array([8, 6, 0])

In [82]:
b[1:4,[2]]

array([[8],
       [6],
       [0]])

In [79]:
b[1:4,[2]]

array([[8],
       [6],
       [0]])

In [80]:
b[1:4,2]

array([8, 6, 0])

In [84]:
b[1:4,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [85]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [86]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
x1=x.reshape(3,2)

In [90]:
x1

array([[2, 5],
       [8, 3],
       [6, 1]])