<a href="https://colab.research.google.com/github/j-agrawal/Machine-Learning/blob/master/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np # importing numpy library as np

In [0]:
a=np.array([2,7,1,99,4]) # declaring array a

In [4]:
print(a) # print the value of a 

[ 2  7  1 99  4]


In [5]:
type(a) # print the data type of a 

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14]) # declaring array b

In [7]:
a # print a

array([ 2,  7,  1, 99,  4])

In [8]:
b # print b

array([ 12,  17,  11, 199,  14])

In [9]:
a[0] # print element 0 of array a

2

In [10]:
b[0] # print element 0 of array b

12

In [11]:
a+b # addition on a and b

array([ 14,  24,  12, 298,  18])

In [12]:
a+2 # adding 2 with each value of a

array([  4,   9,   3, 101,   6])

In [13]:
a*2 # multiplying each value of a with 2

array([  4,  14,   2, 198,   8])

In [14]:
a**2 # square of each element of a

array([   4,   49,    1, 9801,   16])

In [0]:
x=np.array([[2,5,8], [3,6,1]]) # define a matrice of 2 x 3

In [16]:
print(x) # print matrix x

[[2 5 8]
 [3 6 1]]


In [0]:
x # print matrix x

In [17]:
x[0] # print 0 row of matrix 0

array([2, 5, 8])

In [18]:
x[0,0] # print element of 0 row and 0 column of matrix x

2

In [19]:
x+7 # adding 7 to each element of x  

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
y=x+7

In [21]:
y

array([[ 9, 12, 15],
       [10, 13,  8]])

In [22]:
x*2 # multiplying matrix x with 2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [23]:
x**2 # finding square of each elememt of x

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [24]:
x**3 # finding cube of each element of x

array([[  8, 125, 512],
       [ 27, 216,   1]])

In [26]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [27]:
x[1]

array([3, 6, 1])

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]])

In [29]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [30]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [25]:
x.shape # print the format of matrix

(2, 3)

In [31]:
z.shape

(4, 2)

In [32]:
z[0:2] # for printing range of rows...

array([[2, 7],
       [3, 8]])

In [33]:
z[0:] # printing all rows
      #x[row:range,column:range]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [34]:
z[0:]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [35]:
z[0:2,0]

array([2, 3])

In [36]:
x[0:,1]

array([5, 6])

In [37]:
x[0:,0:2]

array([[2, 5],
       [3, 6]])

In [38]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [39]:
z[2]

array([2, 9])

In [40]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [41]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [42]:
z[[0,3],[1]]

array([7, 4])

In [43]:
b=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])
b

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [44]:
b.shape

(4, 3)

In [45]:
b[0:4,[1]]


array([[9],
       [2],
       [5],
       [9]])

In [46]:
b[0:4,[2]]


array([[7],
       [8],
       [6],
       [0]])

In [47]:
b[0:,[2]]

array([[7],
       [8],
       [6],
       [0]])

In [48]:
b[1:3,[1]]

array([[2],
       [5]])

In [49]:
b[1:4,2]

array([8, 6, 0])

In [50]:
b[1:4,[2]]

array([[8],
       [6],
       [0]])

In [51]:
b[1:4,[2]]

array([[8],
       [6],
       [0]])

In [52]:
b[1:4,2]

array([8, 6, 0])

In [53]:
b[1:4,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [54]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [55]:
x.reshape(3,2) # change the form of matrix(convert 3 x 2 matrix into 2 x 3)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
x1=x.reshape(3,2)

In [57]:
x1

array([[2, 5],
       [8, 3],
       [6, 1]])

In [58]:
np.full((4,5),9) # enter 9 for all values of 4 x 5 matrix

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [59]:
# print all the function of np containing zero word in their name
for i in dir(np):
    if 'zer' in i:   
        print(i)

count_nonzero
flatnonzero
nonzero
trim_zeros
zeros
zeros_like


In [60]:
[i  for i in dir(np)   if 'zer' in i ] # short trick for the above functionality

['count_nonzero',
 'flatnonzero',
 'nonzero',
 'trim_zeros',
 'zeros',
 'zeros_like']